name: AppScan CodeSweep

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    name: AppScan CodeSweep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
